function galaxy(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Tb='.cache.html',_='/',Ob='255554B63C49AE5761AAB9EF3E17EA44',Pb='3E8ED7AF2198352CF18BDA1DDD9D5031',Qb='421B7FF457A56FA7F616C36FC630146F',Sb=':',ob='::',mc='<script defer="defer">galaxy.onInjectionDone(\'galaxy\')<\/script>',hb='<script id="',Wb='<script language="javascript" src="',rb='=',$='?',Rb='B9A6F93FDC58CDE373C936498D01B87A',tb='Bad handler "',Ub='DOMContentLoaded',jb='SCRIPT',gb='__gwt_marker_galaxy',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Y='end',Q='galaxy',eb='galaxy.nocache.js',nb='galaxy::',Ib='gecko',Jb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Mb='hosted.html?galaxy',Hb='ie6',Gb='ie8',xb='iframe',ab='img',yb="javascript:''",Lb='loadExternalRefs',lb='meta',Ab='moduleRequested',X='moduleStartup',Fb='msie',mb='name',Cb='opera',zb='position:absolute;width:0;height:0;border:none',Eb='safari',gc='sc/modules/ISC_Calendar.js',hc='sc/modules/ISC_Calendar.js"><\/script>',$b='sc/modules/ISC_Containers.js',_b='sc/modules/ISC_Containers.js"><\/script>',Vb='sc/modules/ISC_Core.js',Xb='sc/modules/ISC_Core.js"><\/script>',ic='sc/modules/ISC_DataBinding.js',jc='sc/modules/ISC_DataBinding.js"><\/script>',cc='sc/modules/ISC_Forms.js',dc='sc/modules/ISC_Forms.js"><\/script>',Yb='sc/modules/ISC_Foundation.js',Zb='sc/modules/ISC_Foundation.js"><\/script>',ac='sc/modules/ISC_Grids.js',bc='sc/modules/ISC_Grids.js"><\/script>',ec='sc/modules/ISC_RichTextEditor.js',fc='sc/modules/ISC_RichTextEditor.js"><\/script>',kc='sc/skins/Graphite/load_skin.js',lc='sc/skins/Graphite/load_skin.js"><\/script>',db='script',Nb='selectingPermutation',R='startup',fb='undefined',Kb='unknown',Bb='user.agent',Db='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}galaxy=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Cb)!=-1){return Cb}else if(b.indexOf(Db)!=-1){return Eb}else if(b.indexOf(Fb)!=-1){if(document.documentMode>=8){return Gb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Hb}}}}else if(b.indexOf(Ib)!=-1){return Jb}return Kb};u[Bb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};galaxy.onScriptLoad=function(){if(I){q=true;B()}};galaxy.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Lb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Mb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Nb});if(!A()){try{G([Eb],Ob);G([Jb],Pb);G([Hb],Qb);G([Gb],Qb);G([Cb],Rb);K=w[H(Bb)];var M=K.indexOf(Sb);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Tb}catch(a){return}}var N;function O(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(Ub,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ub,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Lb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[Vb]){__gwt_scriptsLoaded[Vb]=true;document.write(Wb+s+Xb)}if(!__gwt_scriptsLoaded[Yb]){__gwt_scriptsLoaded[Yb]=true;document.write(Wb+s+Zb)}if(!__gwt_scriptsLoaded[$b]){__gwt_scriptsLoaded[$b]=true;document.write(Wb+s+_b)}if(!__gwt_scriptsLoaded[ac]){__gwt_scriptsLoaded[ac]=true;document.write(Wb+s+bc)}if(!__gwt_scriptsLoaded[cc]){__gwt_scriptsLoaded[cc]=true;document.write(Wb+s+dc)}if(!__gwt_scriptsLoaded[ec]){__gwt_scriptsLoaded[ec]=true;document.write(Wb+s+fc)}if(!__gwt_scriptsLoaded[gc]){__gwt_scriptsLoaded[gc]=true;document.write(Wb+s+hc)}if(!__gwt_scriptsLoaded[ic]){__gwt_scriptsLoaded[ic]=true;document.write(Wb+s+jc)}if(!__gwt_scriptsLoaded[kc]){__gwt_scriptsLoaded[kc]=true;document.write(Wb+s+lc)}m.write(mc)}
galaxy();